### ISSUE TITLE
sveltekit project set up

### ISSUE THREAD

**Issue by wingsvn** [wingsvn/13-your-tribe-for-life-profile-card#1]

**Comment by wingsvn** [comment]
Voor het creëren van een Sveltekit project heb ik de volgende commands uitgevoerd in de terminal van mijn editor:

* `npm create svelte@latest my-app` _selecteer skeleton project + typescript: no_
* `cd my-app`
* `npm install`
* `npm run dev`

sources:
https://kit.svelte.dev/docs/creating-a-project
https://docs.directus.io/blog/getting-started-directus-sveltekit.html

**Comment by Yu-Jing-van-Gerwen** [comment]
de stappen kloppen precies met de uitleg de issue mag je sluiten
